### ISSUE TITLE
Road map

### ISSUE THREAD

**Issue by burymm** [nemascha/linkcreator#1]
- [x] при нажатии на кнопку создать элемент a и вставить его в элемент #contanier
- [x] добавить текст в ссылку
- [x] Ограничить ввод чисел 1-10
- [x] выводить значение которое ввел пользователь в консоль при нажатии на кнопку
- [x] вывести нужное количество ссылок
- [x] добавить кнопку удалить все ссылки

**Comment by burymm** [comment]
- [x] добавить отступ между ссылкой и кнопкой
- [x] удалить сделать иконкой, чтобы при наведении был текст
- [x] ссылки должны иметь имена типа "новая ссылка 1" и т. д.
- [ ] при нажатии кнопки удалить все ссылки у пользователя должно появляться сообщение на подтверждение. Можно сделать через prompt

**Comment by burymm** [comment]
>  при нажатии на кнопку создать элемент a и вставить его в элемент #contanier
для того чтобы вставить ссылку куда-то. Нужно 1, чтобы был элемнт. Вставить в него. Что-то типа того document.querySelector('#container').appendChild(link)

- [x] после удаление всех ссылок невозможно добавить новые. Исправить.
